
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = true

baseURL = 'https://madsomeness.de/'
title = 'madsomeness'
theme = "PaperMod"


pagination.pagerSize = 15


[languages]
  [languages.de]
    languageName = 'Deutsch'
    languageCode = 'de'
    weight = 1
  [languages.en]
    languageName = '🇬🇧English'
    languageCode = 'en'
    weight = 2


[params]
  ShowReadingTime = true
  # ShowToc = true
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShareButtons = ["reddit", "email", "copy", "linkedin"]
