baseURL = 'https://madsomeness.de/'
title = 'madsomeness'
theme = "PaperMod"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
disableDefaultLanguageRedirect = false

pagination.pagerSize = 15

[params]
  ShowReadingTime = true
  # ShowToc = true
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShareButtons = ["reddit", "email", "copy", "linkedin"]

[languages]
  [languages.de]
    contentDir = "content/de"
    languageName = "Deutsch"
    languageCode = 'de'
    weight = 1

  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    languageCode = 'en'
    weight = 2

  [[languages.de.menu.main]]
    identifier = "home"
    name = "Start"
    url = "/de/"
    weight = 1

  [[languages.de.menu.main]]
    identifier = "posts"
    name = "Beiträge"
    url = "/de/posts/"
    weight = 2

  [[languages.de.menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/de/tags/"
    weight = 3

  [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/en/"
    weight = 1

  [[languages.en.menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/en/posts/"
    weight = 2

  [[languages.en.menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/en/tags/"
    weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"
