baseURL = 'https://madsomeness.de/'
title = 'madsomeness'
theme = "PaperMod"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false

pagination.pagerSize = 15


[languages]
  [languages.de]
    languageName = "Deutsch"
    languageCode = 'de'
    weight = 1

  [languages.en]
    languageName = "English"
    languageCode = 'en'
    weight = 2

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  ShowReadingTime = true
  # ShowToc = true
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShareButtons = ["reddit", "email", "copy", "linkedin"]