// sidebars.ts
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Definiere die gewünschte Reihenfolge
const tierOrder: Record<string, number> = {
  S: 0,
  A: 1,
  B: 2,
  C: 3,
  D: 4,
  E: 5,
  F: 6,
};

const docsDir = path.join(__dirname, 'docs', 'ttRPGs');
const files = fs
  .readdirSync(docsDir)
  .filter((f) => /\.mdx?$/.test(f))
  .map((file) => {
    const source = fs.readFileSync(path.join(docsDir, file), 'utf-8');
    const { data } = matter(source);
    const tier = String(data.tier ?? 'F').toUpperCase();
    const id = `ttRPGs/${file.replace(/\.mdx?$/, '')}`;
    return { id, tier, order: tierOrder[tier] ?? tierOrder.F };
  })
  .sort((a, b) => a.order - b.order)
  .map((item) => item.id);

const sidebars: SidebarsConfig = {
  // Deine Tier‑Sidebar mit S–A–B–…–F
  tiersSidebar: [
    {
      type: 'category',
      label: 'Tier‑Listen',
      items: files,
      collapsed: false,
    },
  ],

  // Rest deiner Docs
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // alle anderen Docs
    },
  ],
};

export default sidebars;
