name: Build and Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

# Grant the Action permission to push to gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout all history so we can push later
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # needed so gh-pages action can see & push existing gh-pages branch

      # 2. Setup Hugo (v3 is the current major)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      # 3. Build the site
      - name: Build site
        run: hugo --minify -d public

      # 4. Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # optional: if you want a custom commit message
          # commit_message: "🛜 site updated: ${{ github.sha }}"
